### ISSUE TITLE
Getting It To Work With Amazon S3

### ISSUE THREAD

**Issue by billh93** [ctrl-freaks/freezeframe.js#10]
How can I get this to work with amazon s3? The image loads but it's just a normal gif. It works normally without implementing Amazons3. The url of the images are like this s3.amazonaws.com/bucket-name/image.jpg. To my understanding in order to get the play button and still frame you convert the image to dataUrl.

This is what I have implemented in my browser policy

```
BrowserPolicy.framing.disallow();
BrowserPolicy.content.disallowInlineScripts();
BrowserPolicy.content.disallowEval();
BrowserPolicy.content.allowInlineStyles();
BrowserPolicy.content.allowFontDataUrl();
BrowserPolicy.content.allowDataUrlForAll();
BrowserPolicy.content.allowOriginForAll('http://localhost:3000');

var trusted = [
    '*.amazonaws.com',
];

_.each(trusted, function(origin) {
    origin = "https://" + origin;
    BrowserPolicy.content.allowOriginForAll(origin);
});
```

I don't know what else to put. I'm not sure if this script is capable with amazon s3. Can anybody help me?

**Comment by chrisantonellis** [comment]
is this still an issue? just updated to v3.0.0. let me know!

**Comment by chrisantonellis** [comment]
give 3.0 a try and report back, this looks CORS related and that issue is fixed in the new release
