### ISSUE TITLE
No callbacks on trigger:'click'

### ISSUE THREAD

**Issue by KjellConnelly** [ctrl-freaks/freezeframe.js#104]
I'm using `react-freezeframe`, and for some reason, when I leave the trigger as `'hover'`, I receive the callback functions. But when I switch them to `'click'`, I get no callbacks. I've set ref `const freeze = useRef()`, and
```jsx
<ReactFreezeframe
  src={src}
  ref={freeze}
...
```

but `onPlay`, `onToggle`, and `onStop` do not work unless I'm on hover. I also tried to switch to `trigger = false`, and manually run `this.freeze.current.start()` to handle it myself. But this doesn't seem to work either (or in my case `freeze.current.start()`)...

It looks like my freeze reference only returns as something like:
```
freeze: {
  current: {
    retry: function
  }
}
```

For some reason, it has no start, stop, or toggle function as I was expecting. Anyone know what the deal is?

**Comment by bytefulness** [comment]
@KjellConnelly did you get any result for your issue?

**Comment by KjellConnelly** [comment]
I don't remember. I think I ended up going with a different solution. Don't remember if I continued using this in a different manner, or dropped it all together though.
