### ISSUE TITLE
only works with self-hosted or CORS-enabled images

### ISSUE THREAD

**Issue by alexyans** [Ctrl-Freaks/freezeframe.js#11]
This might save someone else's time. A canvas that uses foreign-domain images is considered tainted and the same-origin policy will prevent certain methods from working. `Canvas.toDataUrl()` is one of those methods; it will throw an exception and the script will perpetually appear to be loading the gifs.

Consider copying the gifs to your own server first, or opt for another solution.

**Comment by chrisantonellis** [comment]
this is fixed with the new version, go check it out!
