### ISSUE TITLE
Responsiveness

### ISSUE THREAD

**Issue by downhillmedia** [ctrl-freaks/freezeframe.js#12]
GIFs freeze and play as advertised. But they're not responsive.

**Comment by chrisantonellis** [comment]
working on it! i'll post back with the solution once its done

**Comment by chrisantonellis** [comment]
i'm still not totally done with the docs but if you check out the examples here ( http://ctrl-freaks.github.io/freezeframe.js/ ) you can see responsive images are working with a few tweaks. you'll need the new css / js combo, and you'll have to add "freezeframe-responsive" as an additional classname on the element.

**Comment by chrisantonellis** [comment]
o heck ya, this is totally done!
