### ISSUE TITLE
Unable to play the GIF in a loop

### ISSUE THREAD

**Issue by rahul-desai3** [ctrl-freaks/freezeframe.js#13]
I want the GIF to be played in a loop until the user clicks on it to stop. An option for this would be great!

I tried with the config: `'animation_play_duration': Infinity` but then the GIF doesn't play at all.

Here is my code so far on jsBin: https://jsbin.com/zujabevezo/1/edit?html,console,output

**Comment by rahul-desai3** [comment]
Same goes for `'animation_play_duration': Number.POSITIVE_INFINITY`.

**Comment by chrisantonellis** [comment]
this is a good idea! workin on it

**Comment by chrisantonellis** [comment]
all set, grab the latest code and `Infinity` will work as an option for `animation_play_duration` as you described. Thanks for the suggestion :+1:

**Comment by rahul-desai3** [comment]
That was fast! :rocket: 
Thank you!
