### ISSUE TITLE
Start GIF animation once loaded into the browser

### ISSUE THREAD

**Issue by rahul-desai3** [ctrl-freaks/freezeframe.js#14]
An option for this would be nice. I essentially plan to use it like the way Twitter is using it these days - play the GIF animation once it is loaded in the browser and have the user to stop it by clicking on it.

**Comment by chrisantonellis** [comment]
interesting idea! I'll start working on this :+1:

**Comment by chrisantonellis** [comment]
@rahul-desai3 we did some research and this is not possible for a few reasons. Please clarify if i'm incorrect in any of my assumptions!

1. The Twitter functionality you're talking about is pausing a video, not a gif. I couldn't find an example of a GIF with the functionality you described so please link me to one if you can! Twitter is showing and pausing a video... this is not possible with the way freezeframe is built. We can only capture and pause the first frame.

2. I assume you wanted to be able to pause on any frame of the .gif, and this is not possible with freezeframe as mentioned above (we only capture the first frame). At the best we could show the first frame again when the user clicked the image, but this doesn't seem useful.

**Comment by rahul-desai3** [comment]
Gotcha. Thanks for the details 😃
