### ISSUE TITLE
Can't Get It Working :(

### ISSUE THREAD

**Issue by phaze3131** [ctrl-freaks/freezeframe.js#15]
I have my simple page here but I just can't figure out how to get it working, thank you for any help :)

http://travisbklein.com/freeze.html

and this one I have also with the other mehtod:
http://travisbklein.com/freeze2.html

**Comment by phaze3131** [comment]
I figured it out, I wasn't using the "." before the class and thats why!

But now I can't get it working inside of tabs on my website:
https://preview.webflow.com/preview/traviss-supercool-site-1a61fa?preview=81d2edd2ed42ac4fd9ed475b41eec95c

active tab is 2, but image is in tab 1

It can display the image for the active tab, but the inactive tabs, it won't bring the image or the gif up.

Any idea why? might I need to slightly alter the framework code a bit?

Thanks so much for any help  chrisantonellis, super job I love the script!

**Comment by chrisantonellis** [comment]
hey! just responded to your email, but it looks like you caught the issue with the "." before the selector before i responded :) anyways.. gonna look into the issue on your site now

**Comment by chrisantonellis** [comment]
travis, the example on your site isn't working because the gif cannot have its dimensions read and the canvas can't be written to when they have the css "display: none" property applied. You'll either have to call freezeframe on the image when the tab is first clicked, or figure out another way to hide your tabs

**Comment by phaze3131** [comment]
I responded to your email and thank you so much Chris for your help, great script  you wrote :)
