### ISSUE TITLE
In Firefox it works perfectly but it doesn't work in Chrome

### ISSUE THREAD

**Issue by SkyAgency** [ctrl-freaks/freezeframe.js#16]
Test: http://skyagency.pl/testfreeze/
Banner starts at: "GRILL SKONFIGURUJ". It starts at begining in Firefox but Chrome ignores function trigger()

**Comment by chrisantonellis** [comment]
after looking at your code, if i type `img_rek_950x200[currentpage_950x200].trigger();` into the console, the .gif does reset, so it is working the way it should!
