### ISSUE TITLE
Rendering issues with transparent animated GIFs

### ISSUE THREAD

**Issue by licyeus** [ctrl-freaks/freezeframe.js#17]
With transparent animated GIFs (e.g., https://media.giphy.com/media/V6UrkJuSLRH7q/giphy.gif), I am seeing both a gray background and the animated GIF playing behind the frozen frame (see screenshot at https://www.dropbox.com/s/qhjvdlrxy5skeyf/Screenshot%202016-03-13%2014.43.53.png?dl=0). I'm using code from the basic example.

Otherwise, love the library. Thanks much!

**Comment by chrisantonellis** [comment]
this should be an easy one! i'll get working on it

**Comment by mritterhoff** [comment]
@chrisantonellis I can take care of this in the next couple of days if you haven't started on it.

**Comment by chrisantonellis** [comment]
@mritterhoff excellent 👍  we have not started on this one yet but I did put some thought into it..
I was thinking about just hiding the .gif when the canvas is visible but this also affects the state the

**Comment by nickforddesign** [comment]
This is now resolved and will soon be merged with the master branch. 

Thanks to @mritterhoff for his PR on this issue: https://github.com/ctrl-freaks/freezeframe.js/pull/26
