### ISSUE TITLE
Browser support list

### ISSUE THREAD

**Issue by tsouk** [ctrl-freaks/freezeframe.js#18]
Hi all,

Is there a list of supported browsers?
If it depends on the support of the dependencies, please let me know which ones I should check (jQuery, I'm guessing). Otherwise, what browsers do you officially support and will keep supporting in the future?

Thank you

**Comment by chrisantonellis** [comment]
this is a good idea, i'll get working on it and add to the docs. thanks for the suggestion!

**Comment by tsouk** [comment]
Awesome!

The reason I got excited with freezeframe.js is that it seems to support browsers that other libs out there don't. That is Safari. If we are going to use it for a BBC page we would like a list of browsers you know you can support, etc.

Thank you @chrisantonellis !

**Comment by chrisantonellis** [comment]
Freezeframe is working in current versions of Chrome, Firefox and Safari, and I plan to support those browsers and IE from the version where they started supporting the HTML5 Canvas API ( http://caniuse.com/#search=canvas ) That looks like IE9+, almost all version of Chrome and Firefox, and Safari 5+. I also intend on supporting IOS Safari and Android Chrome. I have not done any previous version testing, only current versions.

I also just found bugs in IE 11 IOS Chrome that i'm working on. I'll add the browser support doc to the table ASAP, but i wanted to get you the info sooner!

**Comment by tsouk** [comment]
Ah, that sounds quite a good list @chrisantonellis !
If on unsupported browsers there is no error, or at least nothing very intrusive, and the GIF doesn't play automatically I think we can use it! 
This last one (fallback to no animation) is an accessibility constraint. Animations might be disruptive to some users.

Thank you for this!

**Comment by chrisantonellis** [comment]
@tsouk currently these are features I would have to add but will be working on this week (browser feature detection and graceful degradation if features are unsupported). There is however no "easy" way to provide a fallback for unsupported browsers where the GIF will **not** play, as the pausing of the GIF is a result of freezeframe working correctly. I can however figure out a way to specify a "fallback image" per GIF if this is something that would be of use to you. Please let me know! This would provide the functionality you describe.

**Comment by tsouk** [comment]
The "fallback image" option sounds like a good idea!
Uncontrollable animations are the reason we cannot do GIFs yet. Having a paused fallback gets us over the biggest accessibility concern. When I get some examples going, I will enlist our accessibility experts to look at this, and will give you detailed feedback.

That is, if you want this feature (and probably not much else) to make freezeframe.js a fully accessible GIF library. I believe it is worth it!

**Comment by chrisantonellis** [comment]
@tsouk this is being actively worked on :) expect updates very soon!

**Comment by tsouk** [comment]
awesome @chrisantonellis !
I'll spike a prototype for our new website as soon as possible. I'll get the a11y team to approve and might come up with a pull request for you if we need any changes.
(This could have been in the [ABC's of motion article](https://www.youtube.com/watch?v=H9j-xcxpUn8) if we had it back in August... no worries, we'll get there)

**Comment by nickforddesign** [comment]
Closing because we aren't maintaining 3.x anymore
