### ISSUE TITLE
IE 11 bug with hover event

### ISSUE THREAD

**Issue by chrisantonellis** [ctrl-freaks/freezeframe.js#19]
hover event attached when click event specified in IE 11

**Comment by NikolayTrotsky** [comment]
To solve this problem need to change touch devices detecting
from:
`this.is_touch_device = ('ontouchstart' in window || 'onmsgesturechange' in window);`
to:
`this.is_touch_device = ('ontouchstart' in window || navigator.maxTouchPoints);`

**Comment by nickforddesign** [comment]
Closing because we are no longer maintaining 3.x
