### ISSUE TITLE
is jquery dependency necessary?

### ISSUE THREAD

**Issue by chrisantonellis** [ctrl-freaks/freezeframe.js#23]
lets talk the pros / cons of having jquery as a dependency, and what freezeframe could gain by removing jquery. good idea / bad idea?

**Comment by artaommahe** [comment]
> what freezeframe could gain by removing jquery
it can be used by projects without jquery. currenlty i forced to find another plugin or rewrite jquery usage in freezeframe, because i dont use jquery and will not

**Comment by chrisantonellis** [comment]
@artaommahe sorry to hear that! we have decided internally that we're going to stick with jQuery for browser support 👍

**Comment by nickforddesign** [comment]
@artaommahe We've added support for [Zepto.js](http://zeptojs.com/), as a lightweight alternative to jQuery. If you do not use either, perhaps you'll consider using the packaged version, which includes only the core and event modules of Zepto. That minimal build of Zepto is only 20kb, making the packaged version of freezeframe.js 60kb.
