### ISSUE TITLE
warning and error in examples/index.html due to no elements with class "my_class_4" 

### ISSUE THREAD

**Issue by mritterhoff** [ctrl-freaks/freezeframe.js#25]
In index.html, due to the call to `$('.my_class_4').freezeframe();` we get this warning:

> freezeframe.js:17 ✨ freezeframe.js ✨ : unable to run setup(), no images captured

and this error:

> freezeframe.js:340 Uncaught TypeError: ff.setup(...).attach is not a function

Should there be a 4th example, or should that call be removed?

Additionally, would it be possible to report the selector in the warning message to help with debugging?

**Comment by nickforddesign** [comment]
We just merged a branch that resolves this issue in the demo, there is now a jQuery example. 

And yes, it does report the selector if there are no matches found. Also, the freezeframe jQuery method now has access to the normal freezeframe.js methods `.trigger()` and `.release()`, which are chainable with other jQuery methods.

**Comment by mritterhoff** [comment]
thanks!
