### ISSUE TITLE
Overlay icon on images

### ISSUE THREAD

**Issue by gurumark** [ctrl-freaks/freezeframe.js#27]
How do I give clue to users that the image is animated? An overlay icon which will disappear when hovered or clicked would be very nice enhancement.

**Comment by sauron918** [comment]
+1

**Comment by chrisantonellis** [comment]
good idea! working on it 👍

**Comment by pweigand** [comment]
Take a look at this: #32

**Comment by sido420** [comment]
any updates on this?

**Comment by nickforddesign** [comment]
We finally got around to integrating this feature, sorry it took so long.

Thanks again to @pweigand for the PR, take a look at the updated demo [here](http://ctrl-freaks.github.io/freezeframe.js/)
