### ISSUE TITLE
Text link overlay

### ISSUE THREAD

**Issue by justinmz** [ctrl-freaks/freezeframe.js#30]
Is it possible to have an <a> tag positioned absolutely over the image and trigger the aimation on hover of the <a>. I have a div position relative with the image and <a> in it. I've tried the following but it doesn't seem to work for me.
var ff = new freezeframe('.my_class');
$('a').hover(function(){  
    ff.trigger();
});

**Comment by gera3d** [comment]
I am also interested in this but in my context I have a color overlay div over the gif.
`<div class="image-holder">
				<img class="my_class_1" src="<?php echo $image['url']; ?>" alt="<?php echo $image['alt'] ?>" />
				</div>`

**Comment by justinmz** [comment]
I actually got it working and I also have an overlay. Just set your image-holder as relative, then position absolute the overlay over the gif.

e.g.

<div class="image-holder">
    <img class="my_class_1" src="<?php echo $image['url']; ?>" alt="<?php echo $image['alt'] ?>" />
    <div class="overlay"></div>
</div>

ff = new freezeframe('.my_class_1').capture().setup();
$('.overlay').hover(function(){
    ff.trigger();
},function(){
    ff.release();
});

I wasn't able to create them dynamically in a loop as they each need their own instance created and I wasn't having any luck creating the variables using an array.(I was trying to make them cms editable). Will have another bash at it when I have some more time.

**Comment by gera3d** [comment]
Ok I also got it working with variables.

`<?php if( have_rows('case_study_homepage' , 'option') ): ?>

	<ul>

	<?php while( have_rows('case_study_homepage' , 'option') ): the_row();

		// Get the banner and store it here
		$image = get_sub_field('banner_image' , 'option');
		$link = get_sub_field('banner_link' , 'option');
		$class = get_sub_field('class_number' , 'option');

		?>

		<script type="text/javascript">
		  $(function() {

		    third<?php echo $class; ?> = new freezeframe('.my_class_<?php echo $class; ?>').capture().setup();

		    $('.start<?php echo $class; ?>').hover(function(e) {
		      e.preventDefault();
		      third<?php echo $class; ?>.trigger();
		    });

		    $('.stop<?php echo $class; ?>').mouseleave(function(e) {
		      e.preventDefault();
		      third<?php echo $class; ?>.release();
		    });

		  })
		</script>

		<li class="slide">

			<?php if( $link ): ?>
				<a href="<?php echo $link; ?>" target="_blank">
			<?php endif; ?>
			<div class="image-holder start<?php echo $class; ?> stop<?php echo $class; ?>">
				<div class="col-xs-12 col-md-12 feedperson " style="position: absolute !important; z-index: 99;">
            <div class="col-md-3 col-xs-3 feedperson "><span id=""></span></div>
            <div class="col-md-9 col-xs-9">
                <span class="spacer100"></span><span class="spacer50"></span>
                <h2 class="text-light">Patient Case Study</h2>
                <h4 class="text-light">See How Her Life Changed</h4>
            </div>
        </div>

				<img class=" my_class_<?php echo $class; ?> freezeframe-responsive" src="<?php echo $image['url']; ?>" alt="<?php echo $image['alt'] ?>" />
				</div>
			<?php if( $link ): ?>
				</a>
			<?php endif; ?>

		</li>

	<?php endwhile; ?>

	</ul>

<?php endif; ?>`

**Comment by justinmz** [comment]
Ah clever you used your server side code to generate it. I was attempting to build it with a js array.
Will definitely use your approach :) ... oh and acf ftw

**Comment by gera3d** [comment]
There is probably a cleaner way to do this but this is how I got it working this morning. None developers need to be able to add new banners without me via the dashboard so this is how I got it working.

If you have any suggesting to make it even better I would love to hear it.

**Comment by chrisantonellis** [comment]
I know i'm late responding to this, but it looks like @gera3d was on the right track. The way to accomplish remote starting and stopping of animations is with the trigger and release methods.
