### ISSUE TITLE
Doesn't work with floated images

### ISSUE THREAD

**Issue by edge0703** [ctrl-freaks/freezeframe.js#34]
Everything works fine when I use freezeframe with non-floated images, but the moment I use `float: left` or `float: right` (on the parent element) I can't click the image anymore. Any suggestions?

**Comment by chrisantonellis** [comment]
i'll try to reproduce and report back, thanks!

**Comment by chrisantonellis** [comment]
unable to reproduce, closing this for now, you can open another issue if you want to provide a codepen that reproduces the issue. Thanks!
