### ISSUE TITLE
Is there a way to querySelect all images with file types ending in .gif?

### ISSUE THREAD

**Issue by vincentntang** [ctrl-freaks/freezeframe.js#38]
As I understand you have to specify a freeze-frame class on that `img` gif tag. 

Is there a way to simply querySelect all gifs and have freeze-frame apply the 1st scenario (*animate on hover*)?

e.g. using this css selector or some variant

```
$('img[src$=".gif"]')
```

The reason why I can't add a class is because I'm trying to see if I can use freezeframe.js on a `.md` file type, e.g. I usually just do this

`![](https://i.imgur.com/XYt5jKm.gif)`

**Comment by nickforddesign** [comment]
@vincentntang Sorry for the lack of response on this, this project has been mostly unmaintained for a good while but we are getting back into it as we have a new release coming out soon. 

You can absolutely do what you suggested. Assuming you are using jquery/zepto:

```js
$('img[src$=".gif"]').freezeframe();
```

Or just vanilla js:

```js
new freezeframe('img[src$=".gif"]');
```

This will be a bit different in the upcoming 4.0 release.

Closing this issue, comment if you have any question
