### ISSUE TITLE
FreezeFrame Prevents Videos from Playing in Edge and IE

### ISSUE THREAD

**Issue by downhillmedia** [ctrl-freaks/freezeframe.js#39]
I've used this on a Bootstrap site successfully. Now, in this WordPress site, I get errors on pages with no GIFs and in Edge and IE, videos on the site won't play. Implemented FF in the same way as the Bootstrap site, but WP is a different environment. I can't figure out the cause/solution. 

[https://socialmediadarlingproductions.com/10000-days/](url)

**Comment by nickforddesign** [comment]
@downhillmedia what version of freezeframe are you using? Have you tried the 4.0.0 alpha release?

**Comment by nickforddesign** [comment]
The videos seem to play just fine, I'm closing this issue, feel free to comment
