### ISSUE TITLE
Option for backward playing (or bounce like Boomerang videos)

### ISSUE THREAD

**Issue by xjure** [ctrl-freaks/freezeframe.js#49]

**Comment by nickforddesign** [comment]
This is possible, though it requires actually parsing the gif data, which we currently don't do. We've been discussing a parallel release for this, since it would also add to the bundle size significantly.

**Comment by nickforddesign** [comment]
Unfortunately this is not realistic for freezeframe.js due to CORS restrictions on parsing the data of an image hosted on a different domain.
