### ISSUE TITLE
base64 images are not compressed

### ISSUE THREAD

**Issue by mrDenai** [ctrl-freaks/freezeframe.js#50]
Try to use FileOptimizer or tools like OptiPNG for save ~50% of image size on .ff-overlay and ff-loading-icon background-image and tools like svgomg on svg

Total up to 10% size reduction

**Comment by nickforddesign** [comment]
The SVG was only able to drop about 20 bytes, while sacrificing some precision so I left that alone, but did compress the PNG, thanks for your suggestion!
