### ISSUE TITLE
[react-freezeframe] index.js is missing

### ISSUE THREAD

**Issue by hydrosquall** [ctrl-freaks/freezeframe.js#54]
Hi,

Thanks for the great work on this library! The gallery demo looks very promising.

I did run into 1 issue with the react binding, that the published `dist/` folder doesn't have an `index.js`. Any ideas on how to to fix this?

Minimal example to reproduce: https://codesandbox.io/s/brave-elion-292kt?fontsize=14

**Comment by nickforddesign** [comment]
Fixed in #56

**Comment by hydrosquall** [comment]
Thanks for the quick fix @nickforddesign !
