### ISSUE TITLE
[freezeframe][feature-request] Add destroy method

### ISSUE THREAD

**Issue by hydrosquall** [ctrl-freaks/freezeframe.js#55]
The use-case is to help with cleaning up event listeners if a freezeframe gif is unmounted from the page, to avoid memory leaks.

**Comment by nickforddesign** [comment]
Oops, referenced the wrong issue

**Comment by nickforddesign** [comment]
Added destroy method in [v4.1.0](https://github.com/ctrl-freaks/freezeframe.js/releases/tag/v4.1.0)

**Comment by hydrosquall** [comment]
Fantastic, thank you!
