### ISSUE TITLE
Userscript/browser addon version of this code

### ISSUE THREAD

**Issue by XCanG** [ctrl-freaks/freezeframe.js#61]
Hello, is it possible to make it as userscript or browser addon and inject on a pages?

I have a website with annoying gifs on it. I can't remove them, since they are not AD, but I want to have a cheaper and less consumed and animated page, so that I can run this script on a page and it will set all gif images to static and animate only when hover on it.

**Comment by nickforddesign** [comment]
it's certainly possible to do this, but not exactly on our project roadmap. I can offer some recommendations on how you could do this:

1. For any approach, use the CDN script, which is the simplest way to get started with Freezeframe: https://github.com/ctrl-freaks/freezeframe.js/tree/master/packages/freezeframe#cdn
1. Make a userscript that [injects the script](https://stackoverflow.com/questions/2303147/injecting-js-functions-into-the-page-from-a-greasemonkey-script-on-chrome)
1. Initialize freezeframe on the page using a broad selector, like `'img[src$=".gif"]'`.
