### ISSUE TITLE
Porting to angular/ typescript

### ISSUE THREAD

**Issue by steveboy199** [ctrl-freaks/freezeframe.js#67]
Any change there will be a port to angular/typescript.

**Comment by nickforddesign** [comment]
I'm definitely open to porting to TypeScript and providing types for the libraries, and once that is done, I'm sure an Angular version wouldn't be too difficult to put together.

**Comment by nickforddesign** [comment]
I've ported FreezeFrame core to TypeScript just now, expect a release of that in the near future. Probably I will prioritize bringing TS to the existing packages, then will look into an Angular version.

**Comment by steveboy199** [comment]
Thanks for the port nick, I was able to get freeze frame to work with angular 4.

**Comment by jprinsloo** [comment]
Thanks nick. This also works for Ionic projects (tested on Ionic v3/Angular 5). Any idea when #68 will be merged?

**Comment by nickforddesign** [comment]
I just did some final cleanup and merged #68. I'd recommend using version `5..0.0-beta.1` for now, as I fixed some things with type declarations etc.

I will soon be porting `vue-freezeframe` and `react-freezeframe` to TS, if anyone wants to contribute an Angular version I'm open to it!

**Comment by nickforddesign** [comment]
@jprinsloo sorry it took such a long time, but I finally got around to finishing [angular-freezeframe](https://github.com/ctrl-freaks/freezeframe.js/tree/master/packages/angular-freezeframe)
