### ISSUE TITLE
Animation is not starting from the frame it was paused

### ISSUE THREAD

**Issue by sbalajime** [ctrl-freaks/freezeframe.js#72]
The gifs are stopped and started from starting point. Is it possible to pause and play from the frame it was paused and not from the start?. i searched for documentation but couldn't find enough info.

**Comment by duepi** [comment]
+1

**Comment by nickforddesign** [comment]
This is basically not possible in any practical sense. From a project scope POV, we need to be able to support using gifs that are hosted on any domain (probably the most common use of gifs is from an external domain). The browser prevents you from accessing the actual data of the image if it's on a different domain, so we cannot parse the actual frames.

**Comment by sbalajime** [comment]
Thanks for the information
