### ISSUE TITLE
Error when used with Gatsby: error "window" is not available during server side rendering.

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [ctrl-freaks/freezeframe.js#73]
The project isn't open source 😞  but here's a relevant snippet from a build:

```
5:22:47 PM: error "window" is not available during server side rendering.
5:22:47 PM: 
5:22:47 PM: > 1 | !function(t,n){"object"==typeof exports&&"object"==typeof module?module.exports=n():"function"==typeof define&&define.amd?define([],n):"object"==typeof exports?exports.Freezeframe=n():t.Freezeframe=n()}(window,(function(){return function(t){var n={};function e(r){if(n[r])return n[r].exports;var i=n[r]={i:r,l:!1,exports:{}};return
...
```

![Visually, the top of the request](https://user-images.githubusercontent.com/3335181/91738354-53a5c180-eb7e-11ea-98b5-c5a90ac3425f.png)
[gatsby-log.txt](https://github.com/ctrl-freaks/freezeframe.js/files/5151215/gatsby-log.txt)

**Comment by nickforddesign** [comment]
Sounds like this is just a general issue with SSR compatibility with libraries that use browser-only APIs.

Have you looked at https://github.com/gatsbyjs/gatsby/issues/309?

It's not specific to this library, so I'm closing for now.

**Comment by JoshuaKGoldberg** [comment]
@nickforddesign I have looked at that 😄 and while the general error isn't specific to this library, the issue is that freezeframe.js accesses the `window` object immediately - regardless of the runtime it's working in.

Generally, the solution for getting code that tries to do that is to have it either:
* Check for whether `typeof window !== "undefined"` (e.g. https://github.com/gatsbyjs/gatsby/issues/309#issuecomment-302043875)
* Switch to async loading behavior such as `componentDidMount` (e.g. https://github.com/gatsbyjs/gatsby/issues/309#issuecomment-373359887)

More recently, [`globalThis`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/globalThis) is also a useful strategy.

Would you be open to any of these changes, and if so, could you please reopen this issue? There is behavior done in this library that makes it difficult to use in frameworks such as Gatsby.

**Comment by nickforddesign** [comment]
Thanks for clarifying, I will look at this

**Comment by JoshuaKGoldberg** [comment]
Thank you very much! I'd be happy to help / send a PR / etc., if it's useful at all.

**Comment by jonrrivera** [comment]
hi everybody, I'm getting the same error when using next.js. I tried defining 
`
  if (typeof window !== "undefined") {
       new Freezeframe();
  }
`
which removed the 'window not defined error', but now the project is not compiling. Please let me know if you need any further clarification. thank you!

**Comment by jonrrivera** [comment]
https://www.npmjs.com/package/react-freezeframe !!

**Comment by Chinomso1995** [comment]
Did anyone manage to find a way around this for gatsby projects.

**Comment by nickforddev** [comment]
in general I'd recommend that SSR be skipped for this components, even JSDOM doesn't fully implement the canvas APIs required. So, whatever SRR framework you are using, let it skip freezeframe components.
