### ISSUE TITLE
[ReactFreezeframe] Jest import issue - Cannot use import statement outside a module

### ISSUE THREAD

**Issue by steoo** [ctrl-freaks/freezeframe.js#74]
While running jest tests are failing because of this error, does anyone has the same issue?

    SyntaxError: Cannot use import statement outside a module

      1 | import React, { Component, Fragment } from 'react';
    > 2 | import ReactFreezeframe from 'react-freezeframe';
        | ^
      3 | import PropTypes from 'prop-types';
      4 | import classnames from 'classnames';

**Comment by nickforddesign** [comment]
Have you tried this? https://medium.com/@fredriccliver/syntaxerror-cannot-use-import-statement-outside-a-module-69182014b8c6

**Comment by gerhat** [comment]
@steoo I have this issue as well. Any workarounds?

**Comment by gerhat** [comment]
Actually I get `SyntaxError: Unexpected identifier` for the same line.

**Comment by sarahbilly** [comment]
I also have this issue

**Comment by nickforddev** [comment]
this is just a matter of properly configuring your jest config, closing
