### ISSUE TITLE
anyway to autoplay the GIFs?

### ISSUE THREAD

**Issue by mas-iota** [ctrl-freaks/freezeframe.js#77]
I am using vue-freezeframe, I cannot find an option to autoplay GIF, I tried to call the component's start function, it does autoplay then after re-scaling it gets paused. Please see below GIF

![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/16165616/92743989-bfabd500-f389-11ea-85fa-334e706d2f25.gif)

**Comment by maxrottersman** [comment]
I'm having a similar problem.  My GIF won't start on page load.  The Stop Start buttons from the example code work fine.  I've tried all variations of:

//manual.toggle();
//manual.stop();
manual.start();
document.querySelector('.start').click();

**Comment by mas-iota** [comment]
@maxrottersman I gave up using the autoplay, however, I think what interrupts the autoplay is the `responsive: true` option. When it gets scaled to width: 100% interruption occurs. Try to disable the responsive option and see if it gets fixed, then do a workaround to make it scale 100% width.

here's what I ended up with: https://trends.jawab.app/Mahmoud-8o/post/5f60d859357c0

**Comment by maxrottersman** [comment]
Thanks! Yes, when I set responsive: false it runs on page load, but then I can't get the buttons to work, even if I try to set responsive back to true multiple ways.  I'm no js expert.

**Comment by nickforddesign** [comment]
I'm wondering what you are hoping to accomplish here. If you are looking to autoplay the gif, and then allow the user to pause it on click, that is a new feature that will have to be considered in the core library.

**Comment by maxrottersman** [comment]
I don't look a gift-horse in the mouth ;)  Yes, I want it to start as autoplay and then have some way for a person to "freeze" the frame so they can look at it more closely.  My animated GIFs are charts.  If they have to hit a button to start, I'd just as soon create HTML movies or JS slide shows.  Anyway, I've moved on.  But if the developer creates this feature I'll revisit.

**Comment by mas-iota** [comment]
@nickforddesign Nothing much, except for (I will write the same issue again):

1. GIF is getting paused after programmatically playing it.
2. As @maxrottersman has mentioned, setting responsive to false disables controls somehow.

It's up to you not to add such a feature, but I think it's important to fix issues found in the "core library"
cheers

**Comment by nickforddesign** [comment]
An important limitation of this library is that it is not able to actually "pause" a gif on a frame other than the first frame. This is due to browser security in regards to CORS and while not all gifs are hosted on a different domain than your own, it is an important enough use-case for us to keep it simple. 

If this limitation is a deal breaker for you, I will probably close the issue. If not, let me know and I can add an autoplay feature that allows for clicking to "pause" gif (albeit on the first frame).

**Comment by maxrottersman** [comment]
Thanks for the update!  I would need it to pause on the frame they're looking at.  It seems yes, you should close this issue, but I hope  you put these issues in your documentation or that example page. Maybe say you can't have a GIF start and then pause it.  But you can use your great library to play and pause them if one likes.   Here's the piece I wrote on creating animated GIFs in Excel, though I pulled back and mostly cover creating stand alone GIFs.

https://medium.com/@maxrottersman/animated-chart-gifs-excel-creator-104894d15d01?source=friends_link&sk=ac149e406a4f090d681b76c004555a6d

Again, thanks for the library!  It may still come in handy for me one day!

**Comment by mas-iota** [comment]
No problem getting back to the first frame in my case. Thanks for the efforts!

**Comment by nickforddesign** [comment]
Fair enough, I will add more clarification to the documentation! Maybe at some point if I have time I can create a special version of Freezeframe intended for gifs that you host on your own domain, which would allow for actual frame parsing and pausing on a specific frame.

I've added a ticket to update the docs: https://github.com/ctrl-freaks/freezeframe.js/projects/1#card-47483175

Thanks! Lmk if there's anything else we can do to help.
