### ISSUE TITLE
React: Module not found: Can't resolve 'freezeframe'

### ISSUE THREAD

**Issue by jonrrivera** [ctrl-freaks/freezeframe.js#83]
<img width="800" alt="Screen Shot 2020-12-20 at 7 49 41 PM" src="https://user-images.githubusercontent.com/18686388/102737543-8fff5800-42fc-11eb-88f3-a1635d3b872c.png">

getting this error when trying to use this react-freezeframe

**Comment by jonrrivera** [comment]
any help getting this to work on nextjs ?

**Comment by nickforddesign** [comment]
I'm just guessing here initially, but from what I've seen, server side rendering generally doesn't support al of the DOM APIs, especially things like SVG and Canvas. Can you try to import the component without rendering it server-side?

https://nextjs.org/docs/advanced-features/dynamic-import#with-no-ssr

**Comment by nickforddesign** [comment]
You may want to try the new major version as well, 5.x, it will make it easier for me to help you troublesheet

**Comment by jonrrivera** [comment]
thanks for the follow-up. I'm getting this now when running the latest react-freezeframe on nextjs

<img width="1010" alt="Screen Shot 2021-01-12 at 12 36 21 PM" src="https://user-images.githubusercontent.com/18686388/104369858-ecf0c700-54d2-11eb-89b8-c066feaa1822.png">

**Comment by siddharthkp** [comment]
@jonrrivera Make sure you have installed both `freezeframe` and `react-freezeframe`

```
yarn add freezeframe react-freezeframe
```

**Comment by nickforddesign** [comment]
@jonrrivera did this ^ resolve your issue? If you are using SSR there are some other obstacles, you probably will want to not SSR the freezeframe components because they use DOM APIs that are simply not implemented in js-dom, like canvas.

https://stackoverflow.com/questions/53139884/next-js-disable-server-side-rendering-on-some-pages

**Comment by KjellConnelly** [comment]
If you are using nextjs, try:

```javascript
import dynamic from 'next/dynamic'
const ReactFreezeframe = dynamic(()=> import('react-freezeframe'))
```
