### ISSUE TITLE
freezeframe is not working with image inside Bootstrap4 tab-pane (only in tab-pane active)

### ISSUE THREAD

**Issue by bairog** [ctrl-freaks/freezeframe.js#86]
Hello.
My goal is to implement some tabs with images inside each tab (each image with freezeframe functionality).
I've tried to use **freezeframe** with image that is placed inside Bootstrap4 **tab-pane**. My code is the following:
```
<div>
    <ul class="nav nav-pills text-warning">
        <li class="nav-item">
            <a class="nav-link active" href="#tab-first" data-toggle="tab">First Tab</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#tab-second" data-toggle="tab">SecondTab</a>
        </li>
    </ul>

    <div class="tab-content">
        <div class="tab-pane active" id="tab-first">
            <div style="overflow: auto;  max-height: 650px;">
                <img class="freezeframeWithOverlay" src="http://static1.squarespace.com/static/51c748abe4b0c275d0aa86bf/55f96e21e4b0f86680e762dc/56aa551b8b38d446e39e933b/1454003533097/.gif" />

                <script>
                    new Freezeframe('.freezeframeWithOverlay', {
                        overlay: true
                    });
                </script>
            </div>
        </div>
        <div class="tab-pane" id="tab-second">
            <div style="overflow: auto;  max-height: 650px;">
                <img class="freezeframeWithOverlay" src="http://static1.squarespace.com/static/51c748abe4b0c275d0aa86bf/56141631e4b0095d43132f02/5614164be4b0652b31fbd0a5/1444744817955/parislove9801.gif" />
                <script>
                    new Freezeframe('.freezeframeWithOverlay', {
                        overlay: true
                    });
                </script>
            </div>
        </div>
    </div>
</div>
```
The result is that for image on the **First Tab** freezeframe is working correctly, but for **First Tab** only overlay icon is drawn (no image).
[**JSFiddle link**](https://jsfiddle.net/bairog/haqg2ctn/27/)

P. S. Same code is working correctly whrn images are not placed inside **tab-pane**.

Is that by design or a bug? Or maybe I'm missing something?
Thank you in advance.

**Comment by bairog** [comment]
My goal is to implement tabs with images on each tab (each image with freezeframe functionality).
I've tried this CSS/JavaScript example from [W3School.com](https://www.w3schools.com/howto/tryit.asp?filename=tryhow_js_tabs)
But again only overlay icon is drawn (no image). Looks like the problem is because of  `display: none;` setting for all inactive tabs. Is there any workaround for this?

**Comment by nickforddesign** [comment]
The problem is that the tabs are hiding the elements that Freezeframe needs (the images), when your JS is executed. You need to figure out how to either listen for an event that toggling the tabs triggers, or you could maybe watch for the "active" class being added to `.tab-pane`
