### ISSUE TITLE
ReactFreezeframe not working with Server-Side Rendering

### ISSUE THREAD

**Issue by kaylabranch** [ctrl-freaks/freezeframe.js#89]
Hi all,
I've got it working perfectly on my local (non server-side) instance, but when I try to run the code on the server I get a React minified #130 error. Has anyone had any luck running this SS? I'm assuming it has something to do with canvas, or the window object.

**Comment by nickforddesign** [comment]
In my experience with SSR + Vue, the easiest solution was to not render components that use canvas or svg APIs, for example, server side. I'm not sure what framework you are using, guessing next.js? It looks like it is works similarly to how nuxt.js does it under the hood. 

https://stackoverflow.com/questions/53139884/next-js-disable-server-side-rendering-on-some-pages

Let me know if this is helpful. If not I can do some experimenting with next.js or whatever you are using

**Comment by RivkyB** [comment]
Hi, I don't know if this is a similar issue but when I try to load a gif in NextJS I get this error. 

![image](https://user-images.githubusercontent.com/59144428/122414003-d1438e00-cf54-11eb-9e6b-11e981065881.png)

I am using this loader in my `next.config.js `
`const withAssetsImport = require("next-assets-import");
module.exports = withAssetsImport();`

https://github.com/sayuti-daniel/next-assets-import

**Comment by KjellConnelly** [comment]
I'm having this same issue :(

**Comment by julianjca** [comment]
I use dynamic import with `ssr: false` to make it work with next.js
```javascript
import dynamic from 'next/dynamic';

const ReactFreezeframe = dynamic(() => import('react-freezeframe'), {
  ssr: false,
});

```

**Comment by nickforddev** [comment]
yes because this library uses browser APIs you should disable SRR for any components that use FreezeFrame
