### ISSUE TITLE
Is it possible to play the animation a single time (no loop) ?

### ISSUE THREAD

**Issue by danieljaguiar** [ctrl-freaks/freezeframe.js#91]
I want to click in the play button and see the animation a single time. 
Then the animation should stop and the play button should appear again.

Basically, no loop. Is it possible?

I am using react:

```
<ReactFreezeframe
    src="/test.gif"
    options={{
      overlay: true,
      trigger: "click",
    }}
/>
```

**Comment by nickforddev** [comment]
No, unfortunately this is not even possible in the browser without significant caveats, it is out of scope for this library
