### ISSUE TITLE
Problem with Freezeframe.js inside Bootstrap 5 Modal 

### ISSUE THREAD

**Issue by hmgill** [ctrl-freaks/freezeframe.js#99]
Hello, 

I have a problem with getting a freezeframe.js GIF to play inside a Bootstrap 5 modal. 

When the modal is opened, the GIF is stuck at a white frame and the animation won't start. 

The issue is replicated in the JSFiddle below:
[link](https://jsfiddle.net/JoshieTest/b6qjkLus/10/)

Thanks in advance for your help!

**Comment by nickforddev** [comment]
Looks like you might have a race condition where the modal doesn't exist yet when you set up the event bindings.
